### PR TITLE
Add WSO2 logo

### PR DESCRIPTION
**Pull request by erikbledsoe**
Added logo of WSO2 as corporate user of Fluent Bit, by their request

https://github.com/fluent/fluent-bit/issues/9704

### CODE REVIEW

**Review by patrick-stephens — APPROVED** [review]

**Comment by nilushancosta** [comment]
@erikbledsoe thank you for adding the logo. When I checked the Netlify Deploy Preview, I noticed that the WSO2 logo had a lower resolution compared to the others. Would you be able to check?

Screenshot 2024-12-12 at 11 00 35

**Comment by erikbledsoe** [comment]
@nilushancosta Yeah, that looks like crap. Let me see what I can do. Sorry about that.

**Comment by erikbledsoe** [comment]
@nilushancosta That's exactly the reason. I started by using the SVG but was having problems getting it to size correctly in relation to the other logo, so switched formats. I'll go back to the SVG and figure out the sizing issue.

**Comment by erikbledsoe** [comment]
@nilushancosta should be better now https://github.com/fluent/fluent-bit-website-hugo/pull/72

**Comment by nilushancosta** [comment]
Yes it is. Thank you @erikbledsoe !

**Pull request merged**
