### PR TITLE
Use Google Analytics 4 (GA4) ID

### PR DESCRIPTION
**Pull request by chalin**
- Contributes to #22

/cc @nate-double-u

### CODE REVIEW

**Comment by erikbledsoe** [comment]
This was achieved through the GA UA to GA4 migration process. So this could probably be closed.

**Comment by chalin** [comment]
> This was achieved through the GA UA to GA4 migration process. So this could probably be closed.

Hi @erikbledsoe - no, this was part of the migration process, but it didn't get merged, and so the migration isn't complete.

The website has active GA4 tags in use (but not the CNCF tag), so either someone set them up or they were the ones that Google automatically created.

/cc @caniszczyk

**Comment by erikbledsoe** [comment]
@chalin Ah, my bad. Didn't realize that was the CNCF tag. 
@edsiper can you merge this?

**Comment by edsiper** [comment]
merged, thanks!

**Comment by chalin** [comment]
Thanks @edsiper and @erikbledsoe. As mentioned in

- #22 

... the docs also need to be updated to use `G-93T2VC0VBC`. The site is "powered by GitBook". Can one of you change the GA ID being used by that site?

**Comment by chalin** [comment]
@edsiper @erikbledsoe - the same is true of the pending task (relative to the GitBook `docs` subdomain) mentioned in:

- https://github.com/fluent/fluentd-website/issues/243

Can you here there as well?

**Comment by erikbledsoe** [comment]
@chalin I just tried adding a second Google tag into the GitBook GA plugin (on the Fluent Bit site) and it seems not to work—it stopped sending any data. I couldn't find any documentation to suggest that it would (or wouldn't), but I thought I'd try.

Perhaps we could [combine the two tags](https://support.google.com/google-ads/answer/12329709?hl=en-AU)? I've never tried that; do you have experience with it?

**Comment by chalin** [comment]
@erikbledsoe - right, I'm not surprised that you couldn't add more than one site tag.

Yes, I can connect other site tags to the main CNCF one. I used that feature during GA4 migration to link back to UA properties.

Which IDs would you like me to connect to?

**Comment by erikbledsoe** [comment]
@chalin 
G-GJ6DCMDH4N

**Comment by chalin** [comment]
Done: connected. Can you try again? Thanks @erikbledsoe

**Pull request merged**
