### PR TITLE
blog-fluent-bit-v3

### PR DESCRIPTION
**Pull request by erikbledsoe**
Adds the announcement about Fluent Bit v3 to the blog. Cross-posted from calyptia.com. I have it configured so that the post will nt be visible on the site until 2024-03-19.

### CODE REVIEW

**Comment by erikbledsoe** [comment]
@edsiper @agup006 @patrick-stephens Desn't need to be reviewed today, but needs to be done before EOD on Monday. I have the post configured so it will not display on the site until the 19th.

**Comment by edsiper** [comment]
@erikbledsoe how can I see the visual changes ? I tried the preview link but I cannot see it

**Comment by erikbledsoe** [comment]
@edsiper At least that means the configuration to not display the post until the 19th is working. 🤣

What I had to do on my local environment was change the publishDate value in the metadata section to today or before and then view it. I assume you could do the same for the commit, then just make sure to change it back before approving the PR.

**Comment by edsiper** [comment]
got it thank you

**Pull request merged**
